version: '2'

services:
  opp-service:
    image: opp-service
    ports:
      - "8888:8080"
    networks:
      - opp-net
    depends_on:
      - mysql
      - couchdb
    links:
      - mysql:mysql
      - couchdb:couchdb
  ui:
    build: ./nginx
    links:
      - opp-service:opp-service
    volumes:
      - ./opp-ui:/var/www/opp
      - nginxCerts:/var/certs
    ports:
      - "443:443"
      - "80:80"
    networks:
      - opp-net
    environment:
      - SSL_CERT_INFO="C=US/ST=MA/L=Boston/O=MyOrg/OU=Performance Team/emailAddress=craig@myteam.org"
      - SSL_DH_SIZE=2048 #Diffie-Hellman size (extra ssl security - slow to generate)
      - NGINX_HOST_UI=opp-ui.mydomain.com
      - NGINX_HOST_SVC=opp-svc.mydomain.com
      - NGINX_PORT=443
    #command: /bin/bash -c "envsubst '$$NGINX_HOST_UI $$NGINX_HOST_SVC $$NGINX_PORT' < /etc/nginx/conf.d/opp.template > /etc/nginx/conf.d/opp.conf && nginx -g 'daemon off;' && chown -R nginx:nginx /var/www/opp"
  couchdb:
    build: ./couchdb
    volumes:
      - couchdbData:/usr/local/var/lib/couchdb
      - ./opp-service/db/couchdb:/docker-entrypoint-initdb.d
    ports:
      - "5984:5984"
    networks:
      - opp-net
  mysql:
    image: mysql:5.6
    restart: always
    ports:
      - 3306:3306
    networks:
      - opp-net
    environment:
      - MYSQL_ROOT_PASSWORD=Pa$$word!
      - MYSQL_DATABASE=opp
      - MYSQL_USER=oppuser
      - MYSQL_PASSWORD=opppass
    volumes:
      - mysqlData:/var/lib/mysql
      - ./opp-service/db/mysql/schema:/docker-entrypoint-initdb.d
volumes:
  mysqlData:
    driver: local
  couchdbData:
    driver: local
  nginxCerts: 
    driver: local
networks:
  opp-net:
    driver: bridge
  
