# https://github.com/elastic/elasticsearch-docker
# WARNING: must set vm.max_map_count before running on host
# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
FROM docker.elastic.co/elasticsearch/elasticsearch:5.2.2