Ext.define('OppUI.model.loadTestDashboard.LoadTestReportSummary', {
    extend: 'OppUI.model.Base',
    fields: [
        {name: "loadTestId" },
        {name: "callCount" },
        {name: "respAvg" },
        {name: "respMax" },
        {name: "respMedian" },
        {name: "respMin" },
        {name: "respPct75" },
        {name: "respPct90" },
        {name: "respStddev" },
        {name: "totalBytesReceived" },
        {name: "totalBytesSent" },
        {name: "tpsMedian" },
        {name: "tpsMax" },
        {name: "errorCount" },
        {name: "transactionName" },
        {name: "customName1" },
        {name: "customName2" },
        {name: "customName3" },
        {name: "customValue1" },
        {name: "customValue2" },
        {name: "customValue3" },
        {name: "loadSlaGroupId" },
        {name: "slaCustomName" },
        {name: "slaCustomValue" },
        {name: "slaMarginOfError" },
        {name: "slaMax" },
        {name: "slaMedian" },
        {name: "slaMin" },
        {name: "slaName" },
        {name: "slaPct75" },
        {name: "slaPct90" },
        {name: "slaAvg" }
     ]
});