Ext.define('CCPerf.model.ReportGroupLoadTestModel', {
    extend: 'Ext.data.Model',
    fields: [
            {name: "loadTestId" },
            {name: "version" },
            {name: "appUnderTest" },
            {name: "appUnderTestVersion" },
            {name: "comments"},
            {name: "description"},
            {name: "environment"},
            {name: "startTime", type: 'date', dateFormat: 'timestamp'},
            {name: "testName"},
            {name: "testSubName"},
            {name: "testTool"},
            {name: "testToolVersion"},
            {name: "vuserCount"},
            {name: "transactionName"},
            {name: "callCount"},
            {name: "respAvg"},
            {name: "respMax"},
            {name: "respMin"},
            {name: "respMedian"},
            {name: "respPct75"},
            {name: "respPct90"},
            {name: "respStddev"},
            {name: "tpsMedian"},
            {name: "tpsMax"},
            {name: "totalBytesReceived"},
            {name: "totalBytesSent"},
            {name: "slaCustomName"},
            {name: "slaCustomValue"},
            {name: "loadSlaGroupId"},
            {name: "slaMarginOfError"},
            {name: "slaMax"},
            {name: "slaMedian"},
            {name: "slaMin"},
            {name: "slaName"},
            {name: "slaPct75"},
            {name: "slaPct90"},
            {name: "slaAvg"}

     ]
});
