Ext.define('OppUI.model.loadTestDashboard.LoadTestReportSummary', {
    extend: 'OppUI.model.Base',
    fields: [
            {name: "load_test_id" },
            {name: "version" },
            {name: "app_under_test" },
            {name: "app_under_test_version" },
            {name: "comments"},
            {name: "description"},
            {name: "environment"},
            {name: "start_time", type: 'date', dateFormat: 'timestamp'},
            {name: "end_time", type: 'date', dateFormat: 'timestamp'},
            {name: "test_name"},
            {name: "test_sub_name"},
            {name: "test_tool"},
            {name: "test_tool_version"},
            {name: "vuser_count"},
            {name: "transaction_name"},
            {name: "call_count"},
            {name: "resp_avg"},
            {name: "resp_max"},
            {name: "resp_min"},
            {name: "resp_median"},
            {name: "resp_pct75"},
            {name: "resp_pct90"},
            {name: "resp_stddev"},
            {name: "tps_median"},
            {name: "tps_max"},
            {name: "total_bytes_received"},
            {name: "total_bytes_sent"},
            {name: "sla_custom_name"},
            {name: "sla_custom_value"},
            {name: "load_sla_group_id"},
            {name: "sla_margin_of_error"},
            {name: "sla_max"},
            {name: "sla_median"},
            {name: "sla_min"},
            {name: "sla_name"},
            {name: "sla_pct75"},
            {name: "sla_pct90"},
            {name: "sla_avg"},
            {name: "error_count"}
       
     ]
});