Ext.define('OppUI.model.loadtestDashboard.LoadTestSummary', {
    extend: 'Ext.data.Model',
    fields: [
        {name: "loadTestId", mapping: 'load_test_id' },
        {name: "appUnderTest", mapping: 'app_under_test'  },
        {name: "appUnderTestVersion" },
        {name: "comments"},
        {name: "description"},
        {name: "environment"},
        {name: "startTime", type: 'date', dateFormat: 'timestamp', mapping: 'start_time'},
        {name: "endTime", type: 'date', dateFormat: 'timestamp', mapping: 'end_time'},
        {name: "testName", mapping: 'test_name'},
        {name: "testSubName", mapping: 'test_sub_name'},
        {name: "testTool", mapping: 'test_tool'},
        {name: "testToolVersion", mapping: 'test_tool_version'},
        {name: "vuserCount", mapping: 'vuser_count'},
        {name: "transactionName", mapping: 'transaction_name'},
        {name: "totalCallCount", mapping: 'total_call_count'},
        {name: "respAvg", mapping: 'resp_avg'},
        {name: "respMax", mapping: 'resp_max'},
        {name: "respMin", mapping: 'resp_min'},
        {name: "respMedian", mapping: 'resp_median'},
        {name: "respPct90", mapping: 'resp_pct90'},
        {name: "tpsMedian", mapping: 'tps_median'},
        {name: "tpsMax", mapping: 'tps_max'},
        {name: "totalBytesReceived", mapping: 'total_bytes'},
        {name: "totalBytesSent"},
        {name: 'totalBytes', mapping: 'total_bytes'},
        {name: 'totalCallCountTrend', mapping: 'total_call_count_trend'},
        {name: 'respAvgTrend', mapping: 'resp_avg_trend'},
        {name: 'respMedianTrend', mapping: 'resp_median_trend'},
        {name: 'respPct90Trend', mapping: 'resp_pct90_trend'},
        {name: 'tpsMedianTrend', mapping: 'tps_median_trend'},
        {name: 'tpsMaxTrend', mapping: 'tps_max_trend'},
        {name: 'totalBytesTrend', mapping: 'total_bytes_trend'},
        {name: 'errorCount', mapping: 'error_count'}
     ]
});