Ext.define('OppUI.model.loadtestDashboard.LoadTestGroup', {
    extend: 'Ext.data.Model',
    fields: [
        {name: 'load_test_id', mapping: 'summary_trend[0].load_test_id'},
        {name: 'app_under_test', mapping: 'summary_trend[0].app_under_test'},
        {name: 'app_under_test_version', mapping: 'summary_trend[0].app_under_test_version'},
        {name: 'comments', mapping: 'summary_trend[0].comments'},
        {name: 'description', mapping: 'summary_trend[0].description'},
        {name: 'environment', mapping: 'summary_trend[0].environment'},
        {name: 'start_time', type: 'date', dateFormat: 'timestamp', mapping: 'summary_trend[0].start_time'},
        {name: 'test_name', mapping: 'summary_trend[0].test_name'},
        {name: 'test_sub_name', mapping: 'summary_trend[0].test_sub_name'},
        {name: 'test_tool', mapping: 'summary_trend[0].test_tool'},
        {name: 'test_tool_version', mapping: 'summary_trend[0].test_tool_version'},
        {name: 'vuser_count', mapping: 'summary_trend[0].vuser_count'},
        {name: 'transaction_name', mapping: 'summary_trend[0].transaction_name'},
        {name: 'total_call_count', mapping: 'summary_trend[0].total_call_count'},
        {name: 'resp_avg', mapping: 'summary_trend[0].resp_avg'},
        {name: 'resp_median', mapping: 'summary_trend[0].resp_median'},
        {name: 'resp_pct90', mapping: 'summary_trend[0].resp_pct90'},
        {name: 'tps_median', mapping: 'summary_trend[0].tps_median'},
        {name: 'tps_max', mapping: 'summary_trend[0].tps_max'},
        {name: 'total_bytes', mapping: 'summary_trend[0].total_bytes'},
        {name: 'total_call_count_trend', mapping: 'summary_trend[0].total_call_count_trend'},
        {name: 'resp_avg_trend', mapping: 'summary_trend[0].resp_avg_trend'},
        {name: 'resp_median_trend', mapping: 'summary_trend[0].resp_median_trend'},
        {name: 'resp_pct90_trend', mapping: 'summary_trend[0].resp_pct90_trend'},
        {name: 'tps_median_trend', mapping: 'summary_trend[0].tps_median_trend'},
        {name: 'tps_max_trend', mapping: 'summary_trend[0].tps_max_trend'},
        {name: 'total_bytes_trend', mapping: 'summary_trend[0].total_bytes_trend'},
        {name: 'sparkline90'},
        {name: 'sparkline50'}
     ]
});